import { ReactElement } from 'react';
import SideBar from '@ui/SideBar';
import Head from 'next/head';
import { Layout } from 'src/layouts';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="container mx-auto flex h-60 bg-gray-50">
        <div className="w-[30%]">
          <SideBar />
        </div>
        <div className="w-full"></div>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
